language: python
install:
  - pip install flake8
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"
before_script:
  - "flake8"
  - sudo locale-gen fa_IR
script: python t/test.py
matrix:
    allow_failures:
        - python: "3.2"
        - python: "2.6"
        - python: "nightly"
